export const SPECWEFT_MCP_TOOL_NAMES = [
  "specweft.prepare_task",
  "specweft.get_memory_index",
  "specweft.get_memory_digest",
  "specweft.restore_requirement",
  "specweft.recommend_skills_for_task",
  "specweft.get_skill_context_index",
  "specweft.read_skill_detail",
  "specweft.bootstrap_session",
  "specweft.get_project_profile",
  "specweft.get_project_readiness",
  "specweft.get_project_settings",
  "specweft.update_project_settings",
  "specweft.get_agent_activity",
  "specweft.recommend_project_tools",
  "specweft.get_capability_center",
  "specweft.get_runtime_assembly",
  "specweft.get_recording_status",
  "specweft.start_work_segment",
  "specweft.get_work_segment_status",
  "specweft.complete_work_segment",
  "specweft.get_memory_timeline",
  "specweft.get_requirement_dossier",
  "specweft.review_current_diff",
  "specweft.record_current_diff",
  "specweft.save_session_memory",
  "specweft.recall_sessions",
  "specweft.create_memory_handoff",
  "specweft.recommend_marketplace_mcps",
  "specweft.install_marketplace_mcp",
  "specweft.recommend_marketplace_skills",
  "specweft.check_marketplace_skill_updates",
  "specweft.install_marketplace_skill",
  "specweft.apply_project_mcp",
  "specweft.apply_project_skill",
] as const;

export type SpecWeftMcpToolName = typeof SPECWEFT_MCP_TOOL_NAMES[number];
